version: "3"

services:
  unifi:
    container_name: unifi
    image: tbowman01/unifi:latest
    volumes:
      - '/data/unifi/:/unifi'
    restart: unless-stopped
    networks:
      default:
        # static IP address for unifi controller
        ipv4_address: 172.16.10.254

networks:
  default:
    driver: bridge
    ipam:
     config:
       # your chosen docker network here
       - subnet: 172.16.10.0/24
